# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='complete_location',
            field=models.TextField(default=' '),
        ),
    ]
