# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_city_complete_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='complete_location',
            field=models.TextField(),
        ),
    ]
