# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_category_skill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='SkillCategory',
        ),
    ]
