# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20161028_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill',
            new_name='category',
        ),
    ]
