# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20161026_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='profiles/static/profiles/avatars/'),
        ),
    ]
