# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20161027_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
